services:
  app:
    build: .
    volumes:
      - ./app/frontend:/var/www/html/frontend
      - ./app/backend:/var/www/html/backend
      - ./config/virtualhosts/peliculas.paas.com.conf:/etc/apache2/sites-enabled/peliculas.paas.com.conf
      - ./config/virtualhosts/peliculas.paas.api.com.conf:/etc/apache2/sites-enabled/peliculas.paas.api.com.conf
    ports:
      - "80:80"
    links:
      - db
  db:
    image: mysql:8.0.35-debian
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=films
    volumes:
      - ./config/mysql_dump:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql #Opcional
volumes:
  mysql-data: #Opcional (si queremos mantener los datos de la base de datos)